import {ArrowUpRight,ArrowRight,HeartPulse,ChartNoAxesCombined,Database,ShieldCheck,GraduationCap,Award,MapPin,Mail,Code2,Stethoscope,Download,Check} from 'lucide-react';
import {experiences,skillGroups,education,certifications,profile} from '@/data/portfolio';
import SectionHeading from './SectionHeading';
import Reveal from './Reveal';
import SocialLinks from './SocialLinks';
import Logo from './Logo';
const specialties=[
 {Icon:Stethoscope,title:'Clinical Knowledge',text:'A Pharm.D. foundation in patient information, medications, laboratory results, clinical safety, and multidisciplinary healthcare teams.'},
 {Icon:ChartNoAxesCombined,title:'Data Analytics',text:'SQL, Python, SAS, Power BI, Tableau, and Excel for cleaning, validation, analysis, reporting, and visualization.'},
 {Icon:HeartPulse,title:'Healthcare Informatics',text:'Connecting clinical research data, healthcare quality, confidential information, and healthcare information workflows.'},
 {Icon:ShieldCheck,title:'Research & Compliance',text:'Working with HIPAA, IRB, GCP, CTMS, CDISC standards, Pinnacle 21, and FDA submission support.'}
];
export function About(){return <section id="about" className="section container"><div className="about-intro"><SectionHeading eyebrow="ABOUT ME" title="Where clinical knowledge meets data."/><div className="about-copy"><p>I bring two perspectives to healthcare information: <strong>the clinician’s understanding of the person behind the record</strong> and the analyst’s attention to the data within it.</p><p>With a Doctor of Pharmacy background and a Master’s in Healthcare Informatics, my experience spans clinical care, clinical research, and healthcare data analytics. I work across data quality, visualization, and regulatory documentation to make complex information clear, accurate, and useful.</p></div></div><Reveal className="specialty-grid">{specialties.map(({Icon,title,text},i)=><article className="card specialty-card" key={title}><div className="card-top"><span className="icon-box"><Icon size={23} strokeWidth={1.6}/></span><span className="card-number">0{i+1}</span></div><h3>{title}</h3><p>{text}</p></article>)}</Reveal></section>}
export function Skills(){const icons=[Code2,ChartNoAxesCombined,Database,HeartPulse,ShieldCheck];return <section id="skills" className="section section-tint"><div className="container"><div className="section-split"><SectionHeading eyebrow="EXPERTISE" title="Skills & Tools"/><p>A clinical foundation.<br/>An analytical toolkit.</p></div><Reveal className="skills-grid">{skillGroups.map((group,i)=>{const Icon=icons[i];return <article className={'card skill-card skill-'+i} key={group.title}><div className="skill-title"><span className="icon-box"><Icon size={23} strokeWidth={1.5}/></span><h3>{group.title}</h3></div><div className="chips">{group.items.map((s,n)=><span key={s}><span className="chip-symbol" aria-hidden="true">{i===0?['Py','SQL','R','SAS'][n]:<Check size={12}/>}</span>{s}</span>)}</div></article>})}</Reveal></div></section>}
export function Experience(){return <section id="experience" className="section container"><SectionHeading eyebrow="CAREER" title="Professional Experience" description="From understanding patient care to bringing clarity to clinical and research data."/><div className="timeline">{experiences.map((job,i)=><Reveal key={job.company}><article className="experience-row"><div className="experience-date"><span className="timeline-node"/><span className="role-order">0{i+1}</span><p>{job.dates}</p><span><MapPin size={14}/>{job.location}</span>{job.current&&<span className="current-role">Current role</span>}</div><div className="card experience-card"><div className="experience-heading"><div><p className="company">{job.company}</p><h3>{job.role}</h3></div><span className="experience-icon">{i===0?<Database size={24}/>:i===1?<ChartNoAxesCombined size={24}/>:<Stethoscope size={24}/>}</span></div><ul>{job.bullets.map(b=><li key={b}>{b}</li>)}</ul><div className="tags">{job.tags.map(t=><span key={t}>{t}</span>)}</div></div></article></Reveal>)}</div></section>}
export function HealthcareDataSection(){const concepts=[{Icon:Database,label:'Clinical Data',title:'Context comes first.',text:'Cleaning, validating, organizing, and understanding clinical and research information while maintaining quality and confidentiality.'},{Icon:ChartNoAxesCombined,label:'Analytics',title:'Make the information clear.',text:'Using analytical and visualization tools to identify patterns and communicate information clearly to multidisciplinary stakeholders.'},{Icon:ShieldCheck,label:'Healthcare Insight',title:'Research & compliance.',text:'Working within structured research and regulatory environments involving HIPAA, IRB, GCP, CTMS, CDISC, and related documentation.'}];return <section className="healthcare-section"><div className="container"><div className="healthcare-heading"><p className="eyebrow"><span/>HEALTHCARE × DATA</p><h2>Where Healthcare<br/>Meets <em>Data.</em></h2><p>The clinical context matters.<br/>So does the quality of the analysis.</p></div><div className="concept-grid">{concepts.map(({Icon,label,title,text},i)=><article className="concept-card" key={label}><div className="concept-node"><Icon size={26} strokeWidth={1.5}/></div>{i<2&&<div className="concept-connector" aria-hidden="true"><span/><ArrowRight size={16}/></div>}<p className="concept-label">0{i+1} / {label}</p><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>}
export function Education(){return <section id="education" className="section container"><SectionHeading eyebrow="ACADEMIC JOURNEY" title="Education" description="Two disciplines. One connected perspective on healthcare."/><Reveal className="education-grid">{education.map((e,i)=><article className={'card education-card education-'+i} key={e.degree}><div className="education-top"><span className="icon-box">{i===0?<GraduationCap size={27}/>:<Stethoscope size={27}/>}</span><span className="education-type">{i===0?'HEALTHCARE INFORMATICS':'CLINICAL FOUNDATION'}</span></div><p className="education-dates">{e.dates}</p><h3>{e.degree}</h3><p className="school">{e.school}</p><div className="education-bottom"><span>{i===0?'Graduate education':'Professional doctorate'}</span><strong>{e.achievement}</strong></div></article>)}</Reveal></section>}
export function Certifications(){return <section id="certifications" className="section section-tint"><div className="container"><SectionHeading eyebrow="CREDENTIALS" title="Certifications & Training"/><Reveal className="cert-grid">{certifications.map((c,i)=><article className="card cert-card" key={c}><span className="cert-icon"><Award size={25} strokeWidth={1.5}/></span><h3>{c}</h3><span className="card-number">0{i+1}</span></article>)}</Reveal></div></section>}
export function Contact(){return <section id="contact" className="section container"><div className="contact-card"><div><p className="eyebrow"><span/>GET IN TOUCH</p><h2>Let’s <em>Connect.</em></h2><p>Interested in discussing healthcare analytics, clinical data, research, or healthcare informatics opportunities? Let’s connect.</p><div className="contact-actions"><a className="button primary" href={'mailto:'+profile.email}>Email Me <ArrowUpRight size={18}/></a><a className="button secondary" href={profile.resume} download><Download size={17}/> Download Resume</a></div></div><div className="contact-details"><span className="contact-label">START A CONVERSATION</span><a className="email-link" href={'mailto:'+profile.email}><Mail size={19}/><span>{profile.email}</span><ArrowUpRight size={17}/></a><p><MapPin size={17}/>{profile.location}</p><SocialLinks includeEmail={false}/><div className="contact-status"><span/>Open to healthcare analytics &amp; informatics opportunities</div></div></div></section>}
export function Footer(){return <footer className="footer"><div className="container"><div className="footer-top"><div><a href="#home" aria-label="Akhila, back to top"><Logo/></a><p>Akhila Amudala Ganesh<br/><span>Healthcare Informatics &amp; Data Analytics</span></p></div><SocialLinks/></div><div className="footer-bottom"><p>© 2026 Akhila Amudala Ganesh. All rights reserved.</p><a href="#home">Back to top <ArrowUpRight size={14}/></a></div></div></footer>}

